### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by nostra13** [Leanplum/Leanplum-Android-SDK#108]
Happened crash on production.
Leanplum SDK: 3.0.0
Android: 4.4.2
Device: LGE Y25

```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by java.lang.OutOfMemoryError
       at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:94)
       at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:132)
       at java.lang.StringBuilder.append(StringBuilder.java:124)
       at org.json.JSONStringer.string(JSONStringer.java:344)
       at org.json.JSONStringer.value(JSONStringer.java:252)
       at org.json.JSONObject.writeTo(JSONObject.java:672)
       at org.json.JSONStringer.value(JSONStringer.java:237)
       at org.json.JSONArray.writeTo(JSONArray.java:602)
       at org.json.JSONStringer.value(JSONStringer.java:233)
       at org.json.JSONObject.writeTo(JSONObject.java:672)
       at org.json.JSONObject.toString(JSONObject.java:641)
       at com.leanplum.a.ab.a(SourceFile:47)
       at com.leanplum.a.ax.s(SourceFile:2640)
       at com.leanplum.a.ax.b(SourceFile:57)
       at com.leanplum.a.ax$3.doInBackground(SourceFile:1457)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

Maybe you can do something with it.

**Comment by Enuviel** [comment]
Thank you @nostra13, we will look on it. Do you have statistic how often does it happen? And this happened only on one device(LGE Y25)?

**Comment by nostra13** [comment]
Quite rare: 2 crashes on one device.

**Comment by milos1290** [comment]
@nostra13 Was the OOM caused by sdk ? or application is already memory hungry and it just happen to crash in our code ?

**Comment by nostra13** [comment]
I can't say for sure but usually our app doesn't consume much memory (~25% of available memory). In this case only 19% RAM was consumed.
So I think you tried to serialize a really huge JSON with `JSONObject.toString()` which caused the OOM. I don't know why you need toString() JSONs but you should avoid to do it with huge ones if it's possible.

**Comment by milos1290** [comment]
I agree, the problem is that for example LGE Y25 is lowDPI phone which most likely allows up to 16MB RAM for app to consume while running. We will investigate more to and see how to avoid it.

**Comment by divyas1102** [comment]
Has there been a resolution for this? What is the recommended workaround that we could use?

**Comment by lucas34** [comment]
Seems fixed in `4.0.2` according to the changelogs
