### ISSUE TITLE
LeanplumPushFcmListenerService crash on Oreo

### ISSUE THREAD

**Issue by dmarcato** [Leanplum/Leanplum-Android-SDK#115]
`LeanplumPushFcmListenerService` always tried to start a `Service` to send the updated token to the backend, but starting from Android Oreo it's not possible to start a `Service` if the app is in the background.
I think the implementation should try to use `JobScheduler` to ensure the token is eventually sent to the backend, since starting a `Service` is not reliable anymore.

**Comment by Enuviel** [comment]
Hi @dmarcato, yes, maybe we should move to JobScheduler in the future. 
Is there any issue right now, that token wasn't sent to the server? 
I will ask our QA team to test this one more time but looks like it works for us, and our backend can receive the token.

**Comment by dmarcato** [comment]
The problem shows up when the token changes and the system calls `onTokenRefresh()`. In that scenario Leanplum starts a `Service` to send the token to the backend, but if the app is in the background Oreo will prevent you to start the `Service` and crash with an `IllegalStateException`:
```
Fatal Exception: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.invoice2go.invoice2goplus/com.leanplum.LeanplumPushRegistrationService }: app is in background uid UidRecord{6038e9c u0a163 RCVR idle change:uncached procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1518)
       at android.app.ContextImpl.startService(ContextImpl.java:1474)
       at android.content.ContextWrapper.startService(ContextWrapper.java:649)
       at com.leanplum.LeanplumPushFcmListenerService.onTokenRefresh(SourceFile:47)
       at com.invoice2go.push.I2GFirebaseInstanceIdService.onTokenRefresh(I2GFirebaseInstanceIdService.kt:15)
       at com.google.firebase.iid.FirebaseInstanceIdService.handleIntent(Unknown Source:12)
       at com.google.firebase.iid.zzg.run(Unknown Source:26)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by Enuviel** [comment]
@dmarcato  do you use Android Studio 3.0?

**Comment by dmarcato** [comment]
If you mean Android Gradle build tools, we are still using 2.3.3

**Comment by Enuviel** [comment]
Fixed at https://github.com/Leanplum/Leanplum-Android-SDK/pull/131
