### ISSUE TITLE
Google Play Services: Results Have Already Been Set crash

### ISSUE THREAD

**Issue by ming13** [Leanplum/Leanplum-Android-SDK#133]
We got a crash recently with such stacktrace.

```
Fatal Exception: java.lang.IllegalStateException: Results have already been set
       at com.google.android.gms.common.internal.zzac.zzw(Unknown Source)
       at com.google.android.gms.internal.zzaaf.setResultCallback(Unknown Source)
       at com.google.android.gms.internal.zzaad$zza.zzb(Unknown Source)
       at com.google.android.gms.internal.zzaad$zza.zzb(Unknown Source)
       at com.google.android.gms.internal.zzaad$zza.zzb(Unknown Source)
       at com.google.android.gms.internal.zzaaq.connect(Unknown Source)
       at com.google.android.gms.internal.zzaaq.zzb(Unknown Source)
       at com.google.android.gms.internal.zzaav.zzb(Unknown Source)
       at com.google.android.gms.internal.zzaat.zzb(Unknown Source)
       at com.google.android.gms.internal.zzary.getLastLocation(Unknown Source)
       at com.leanplum.LocationManagerImplementation.onLocationChanged(SourceFile:436)
       at com.google.android.gms.internal.zzasg$zzb$1.zza(Unknown Source)
       at com.google.android.gms.internal.zzasg$zzb$1.zza(Unknown Source)
       at com.google.android.gms.internal.zzabh.zzwW(Unknown Source)
       at com.google.android.gms.internal.zzabh$zza.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6642)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

Which points to this line.

```java
LocationServices.FusedLocationApi.removeLocationUpdates(googleApiClient, this);
```

The speculative suggestion is that there is some race condition in internal Google Client management, but it is only a guess :-)

**Comment by Enuviel** [comment]
Hi @ming13, 
Thank you for reported this crash!
Yeah, this looks more like some bug on Google side.
We will try to prevent crashes at next release -  https://github.com/Leanplum/Leanplum-Android-SDK/pull/136.
