### ISSUE TITLE
Android Pie 9.0

### ISSUE THREAD

**Issue by simontgs** [Leanplum/Leanplum-Android-SDK#214]
We're running into a 100% fatal crash on our app - built with Unity 2018.2.2 

It runs fine on any Android O/S below 9.0

Fatal Exception
08-14 12:30:09.438: E/AndroidRuntime(11150): java.lang.RuntimeException: Stub!
08-14 12:30:09.438: E/AndroidRuntime(11150): 	at org.apache.http.message.AbstractHttpMessage.<init>(AbstractHttpMessage.java:7)
08-14 12:30:09.438: E/AndroidRuntime(11150): 	at org.apache.http.client.methods.HttpRequestBase.<init>(HttpRequestBase.java:7)
08-14 12:30:09.438: E/AndroidRuntime(11150): 	at org.apache.http.client.methods.HttpEntityEnclosingRequestBase.<init>(HttpEntityEnclosingRequestBase.java:7)
08-14 12:30:09.438: E/AndroidRuntime(11150): 	at org.apache.http.client.methods.HttpPost.<init>(HttpPost.java:8)
08-14 12:30:09.438: E/AndroidRuntime(11150): 	at com.leanplum.internal.SocketIOClient$3.run(SocketIOClient.java:239)

We're using Proguard+Gradle

We're also using Leanplum 4.1.1

Any thoughts on what we could do to work around this?

**Comment by simontgs** [comment]
We're going to try

<uses-library android:name="org.apache.http.legacy" android:required="false"/>

from here..

https://developer.android.com/about/versions/pie/android-9.0-changes-28

**Comment by simontgs** [comment]
uses-library android:name="org.apache.http.legacy" android:required="false"/>

fixed it
