### ISSUE TITLE
Can't use 2.2.3 with AGP 3.0 and Java 1.8 compatibility

### ISSUE THREAD

**Issue by orrc** [Leanplum/Leanplum-Android-SDK#73]
Upgrading to version 2.2.3 of the SDK causes our app to no longer compile, failing during desugaring.

I reproduced this in an empty project: https://github.com/orrc/leanplum-desugar-failure

Sample output:
```
$ ./gradlew clean assembleDebug
Picked up JAVA_TOOL_OPTIONS: -Dapple.awt.UIElement=true
Picked up JAVA_TOOL_OPTIONS: -Dapple.awt.UIElement=true
Picked up JAVA_TOOL_OPTIONS: -Dapple.awt.UIElement=true

Exception in thread "main" java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer$DefaultMethodFinder.visit(DefaultMethodClassFixer.java:471)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.defaultMethodsDefined(DefaultMethodClassFixer.java:319)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visitEnd(DefaultMethodClassFixer.java:88)
        at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
        at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitEnd(InterfaceDesugaring.java:85)
        at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
        at com.google.devtools.build.android.desugar.LambdaDesugaring.visitEnd(LambdaDesugaring.java:150)
        at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
        at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:583)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDesugarForDebug'.
> com.android.build.api.transform.TransformException:
 java.lang.RuntimeException:
  java.lang.RuntimeException:
   com.android.ide.common.process.ProcessException:
    Error while executing java process with main class
    com.google.devtools.build.android.desugar.Desugar with arguments { --input /Users/chris/.gradle/caches/transforms-1/files-1.1/Leanplum-2.2.3.aar/1ed6ef28c361f8637db8e84e2c4d3f8f/jars/classes.jar … }
```

Switching back to version 2.2.2 of the plugin works fine.

I couldn't see any particularly interesting changes between 2.2.2 and 2.2.3, so I'm not sure what the problem is — quite possibly it's an issue with the Android Gradle plugin.

**Comment by milos1290** [comment]
I've looked through reported bugs, it seems that there is an issue with Android Gradle plugin atm. I'm not sure why it works on 2.2.2 and not in 2.2.3 since there weren't any changes to build process. I suggest we wait for next Android Gradle plugin release and see if the issue is fixed.

**Comment by benmarten** [comment]
@milos1290 Is the issue reported at https://github.com/gradle/gradle ? If yes, please post here, so its linked. If not is the issue reproducible so that we can report it there please?

**Comment by milos1290** [comment]
yes, here is one of the reported bugs https://issuetracker.google.com/issues/63265765 same error, different library.

**Comment by benmarten** [comment]
https://github.com/gradle/gradle/issues/2384#issuecomment-313209586
@orrc It seems this is an issue with the Gradle plugin, as mentioned by Milos and in the attached two links... Please check there and reopen in case it is really an issue with Leanplum. Thanks
